name: deploy

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push to dockerhub container registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: make application-prod.yml
        run: |
          cd ./src/main/resources
          touch ./application-prod.yml
          echo "${{ secrets.WRITING_APPLICATION_PROD_YML }}" >> ./application-prod.yml
        shell: bash

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Login to DOCKERHUB Container Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_ACCESS_KEY }}
          password: ${{ secrets.DOCKERHUB_SECRET_KEY }}

      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_CONTAINER_REGISTRY }}/roumo-writing-api:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_CONTAINER_REGISTRY }}/roumo-writing-api:latest
          cache-to: type=inline

  pull_from_registry:
    name: Connect server ssh and pull from container registry
    needs: push_to_registry
    runs-on: ubuntu-latest
    steps:
      - name: Get Github Actions IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Add Github Actions IP to Security group
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: connect ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_KEY }}
          port: ${{ secrets.PROD_PORT }}
          script: |
            sudo docker rm -f $(docker ps -aqf "name=writing-api")
            sudo docker pull ${{ secrets.DOCKERHUB_CONTAINER_REGISTRY }}/roumo-writing-api
            docker run -d -p 8088:8088 -e TZ=Asia/Seoul ${{ secrets.DOCKERHUB_CONTAINER_REGISTRY }}/roumo-writing-api
            docker image prune -f

      - name: Remove Github Actions IP From Security Group
        run: |
          aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
